services:
  nerugaysyabot:
    build: .
    image: sakameow/nerugaysyabot:latest
    container_name: nerugaysyabot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "2112:2112"
    volumes:
      - ./data:/data
